language: php 

php:
  - 7.0

notifications:
  email:
    - dharrya@gmail.com

env:
  - REPORT_EXIT_STATUS=1 NO_INTERACTION=1 TEST_PHP_ARGS=--show-diff

#Compile
before_script:
    - ./travis/compile.sh

# Run PHPs run-tests.php 
script: make test
